# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={},
        ),
    ]
