# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160510_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('table_name', models.CharField(blank=True, max_length=64, null=True)),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('field', models.CharField(blank=True, max_length=64, null=True)),
                ('source_name', models.CharField(blank=True, max_length=256, null=True)),
                ('source_link', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'metadata_test',
            },
        ),
        migrations.CreateModel(
            name='RegionLookupTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_code', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('co_code', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('region', models.CharField(blank=True, max_length=90, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region_lookup_test',
            },
        ),
        migrations.CreateModel(
            name='SubsidyDollarsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('subsidy_dollars', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subsidy_dollars_test',
            },
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'managed': False},
        ),
    ]
